### ISSUE TITLE
Cpptrace verification failed

### ISSUE THREAD

**Issue by soerlemans** [jeremy-rifkin/cpptrace#49]
When I print a stacktrace it does not resolve to any filenames or line numbers.

```
Stack trace (most recent call first):
#0  0x000055c9914ba04b in  at ./debug/crow
#1  0x000055c9914fdc15 in  at ./debug/crow
#2  0x000055c9914fe03f in  at ./debug/crow
#3  0x000055c9914c2e0a in  at ./debug/crow
#4  0x000055c9914cb1c2 in  at ./debug/crow
#5  0x000055c9914cafc9 in  at ./debug/crow
#6  0x000055c9914d6dcc in  at ./debug/crow
#7  0x000055c9914cb1c2 in  at ./debug/crow
#8  0x000055c9914fe6e7 in  at ./debug/crow
#9  0x000055c9914c3df8 in  at ./debug/crow
#10 0x000055c9914cb1c2 in  at ./debug/crow
#11 0x000055c9914cafc9 in  at ./debug/crow
#12 0x000055c9914d6dcc in  at ./debug/crow
#13 0x000055c9914cb1c2 in  at ./debug/crow
#14 0x000055c99145db87 in  at ./debug/crow
#15 0x000055c99145deb7 in  at ./debug/crow
#16 0x000055c99145e071 in  at ./debug/crow
#17 0x00007fc35bb426c9 in  at /lib/x86_64-linux-gnu/libc.so.6
#18 0x00007fc35bb42784 in __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6
#19 0x000055c99145ce40 in  at ./debug/crow
```

When I set:
```cpp
cpptrace::absorb_trace_exceptions(false);
```

When I try to use:
```cpp
cpptrace::stacktrace::current()
```

The following exception is emitted.
```
Cpptrace verification failed at /home/hackerman/crow/debug/_deps/cpptrace-src/src/symbols/symbols_with_libdwarf.cpp:267: void cpptrace::detail::libdwarf::die_object::dwarf5_ranges(F) const [with F = cpptrace::detail::libdwarf::die_object::get_rangelist_entries(int) const::<lambda(Dwarf_Addr, Dwarf_Addr)>]
    VERIFY(wrap(dwarf_attr, die, DW_AT_ranges, &attr) == DW_DLV_OK);
```

No matter which backend I select I get this exception.
I am not familiar with the libraries internals but I assume libdwarf is always used in some way regardless of the backend selected?
I know that the macros are being defined correctly, as when I define a different backend to use the compiler recognizes it.

Cmake cpptrace configuration:
```cmake
FetchContent_Declare(
  cpptrace
  GIT_REPOSITORY https://github.com/jeremy-rifkin/cpptrace.git
  GIT_TAG        v0.2.0-beta2
	SYSTEM
)

add_compile_definitions(
  CPPTRACE_UNWIND_WITH_UNWIND
  CPPTRACE_GET_SYMBOLS_WITH_LIBDL
)

set(CMAKE_CXX_FLAGS_DEBUG
	"-g3 -gdwarf"
)

add_link_options(
	"-ldl"
	"-rdynamic"
)

# On windows copy cpptrace.dll to the same directory as the executable for your_target
if(WIN32)
  add_custom_command(
    TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
    $<TARGET_FILE:cpptrace> $<TARGET_FILE_DIR:${PROJECT_NAME}>
  )
endif()

# Make available:
FetchContent_MakeAvailable(rang tabulate cpptrace)
```

The compiled binary uses dwarf version 5:
```
$ llvm-dwarfdump-16 -r 1 ./debug/crow | head | grep Compile
0x00000000: Compile Unit: length = 0x0012bfd0, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0012bfd4)
```

I tried to fix it by changing the version to dwarf 4 but this did not work.
I am compiling a Debug build in CMake.

I am compiling on debian:
```
$ uname -a
Linux droid 6.1.0-8-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.25-1 (2023-04-22) x86_64 GNU/Linux
```

Since I am on Debian I suspect that this might have to do with my GCC version langging behind or some other tool being out of date.
```
$ gcc --version        
gcc (Debian 13.2.0-4) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I am aware that 6.1 is kind of an old kernel i will try updating to 6.5 and see if that fixes it (I do not think this is a kernel issue though).

**Comment by jeremy-rifkin** [comment]
Hi thank you so much for the report, I’ll look into this. The libbacktrace and addr2line back-ends should avoid the libdwarf stuff in the meantime.

**Comment by jeremy-rifkin** [comment]
Looking at the code, I think I removed that assertion in 93dde93. If use the current tag for main it should work and I'm hoping to do a v0.2 release today or in the next few days.

**Comment by soerlemans** [comment]
```cmake
FetchContent_Declare(
  cpptrace
  GIT_REPOSITORY https://github.com/jeremy-rifkin/cpptrace.git
  # GIT_TAG v0.2.0-beta2
  GIT_TAG origin/main
  SYSTEM
)
```

Pulling from origin/main fixed it.
Thanks for your time!
